In [1]:
import torch

In [9]:
a = torch.randint(0, 8, (12,))
a

tensor([0, 3, 3, 7, 4, 4, 5, 7, 7, 0, 2, 6])

In [5]:
b = a.chunk(2, 1)
b

(tensor([[[[0.1791]]],
 
 
         [[[1.9290]]],
 
 
         [[[1.3371]]]]),
 tensor([[[[-0.4934]]],
 
 
         [[[-1.3503]]],
 
 
         [[[-1.1043]]]]))

In [6]:
test = torch.randn(2, 4, 32, 4)
test

tensor([[[[-0.4214, -0.4255,  0.4008,  1.8314],
          [-1.0398, -0.3010,  0.5899,  2.4503],
          [-0.1412, -0.4531,  0.3766,  1.9251],
          ...,
          [-0.3276,  2.5605, -0.7929, -0.0748],
          [-0.3580, -0.5503,  0.8274, -1.2982],
          [-0.8124,  0.1245,  1.4547, -0.9851]],

         [[ 1.2671,  0.9649, -0.6397,  1.3493],
          [-0.8670,  0.6394,  0.4455, -1.6558],
          [ 0.4590,  0.4766,  1.0744, -0.1543],
          ...,
          [ 0.6113,  0.5581, -0.0172,  0.3203],
          [-1.2533, -0.2097, -0.5630, -0.7948],
          [ 0.2088, -2.0264,  0.8626,  0.7162]],

         [[-0.2794,  1.6232,  0.1270,  0.7934],
          [-0.6794, -0.4460, -0.1387, -0.0236],
          [ 1.7893,  0.7044,  0.5965, -2.0904],
          ...,
          [-0.1731,  0.3245,  0.1655, -0.9163],
          [-0.5938,  0.2514, -0.1803,  0.7624],
          [ 1.3923, -0.4891, -0.3722,  0.4003]],

         [[ 0.9809,  1.6938,  0.7152,  0.0224],
          [-0.9267,  0.3439,  1.4460,